### ISSUE TITLE
Can't start AATU. Error in the event log

### ISSUE THREAD

**Issue by masterrite** [JamesCJ60/AMD-APU-Tuning-Utility#11]
**Describe the bug**
AATU refuses to start after worked fine for a while. Event log shows .NET Runtime and application error (see attached) for AATU.exe

**To Reproduce**
Open AATU as usual

**Desktop (please complete the following information):**
 - OS: Windows 10 Education 19044.1466
 - APU 5800u
 - Version AMD APU Tuning Utility V2.0.5.3

**Additional context**
[AATU Error.txt](https://github.com/JamesCJ60/AMD-APU-Tuning-Utility/files/7874141/AATU.Error.txt)

**Comment by JamesCJ60** [comment]
Hi, try deleting the AATU files in appdata local under JamesCJ and possibly deleting and reinstalling AATU if that does nothing.

**Comment by masterrite** [comment]
Thanks! It worked.
