### ISSUE TITLE
how to reset the apu tuning utility to stop interferring the driver and cause overheating

### ISSUE THREAD

**Issue by Vikaash301** [JamesCJ60/AMD-APU-Tuning-Utility#13]
when i used it it permanently made changes to the driver so whenever i restarted the problem  still exist and whaere is the reset button to put the driver to its orginal  state

**To Reproduce**

**Expected behavior**
83 degress while run only chrome on charging

**Screenshots**

**Desktop (please complete the following information):**
 - windows 11 latest version
 - APU ryzen 5 3450U
 - 

**Additional context**
i din`int even overclock i just put temperature limit to 66 degress

**Comment by JamesCJ60** [comment]
Nothing is set in a driver when using AATU and everything gets reset when restarting ur laptop.
