### ISSUE TITLE
Windows Defender reports that release V2.0.5.4 (Release V2) includes Trojan:Script/Oneeva.a!ml

### ISSUE THREAD

**Issue by ruan92** [JamesCJ60/AMD-APU-Tuning-Utility#16]
**Describe the bug**
When I downloaded V2.0.5.4 (Release V2) Windows Defender deleted the zip archive and reported that it contained a trojan named Script/Oneeva.a!ml

The non-V2 release of V2.0.5.4 did not give this problem.

**Comment by JamesCJ60** [comment]
I have checked the .zip file myself and found nothing of the sorts, there are also websites that are also publishing the .zip file who also found no viruses. I believe it’s just Windows Defender being over curious and trigger happy.
