### ISSUE TITLE
Uninstaller/ How to uninstall?

### ISSUE THREAD

**Issue by Dynodope** [JamesCJ60/AMD-APU-Tuning-Utility#18]
Yeah, new on here because AATU is not showing up in my apps/features in Control panel in Windows 10 Pro 64-bit. AATU is causing my PC to hang/freeze, and I have to hard power off/reboot my Laptop to do anything in Windows again. This occurs anywhere from 15-45 minutes after starting the PC up.

Either add an uninstaller with the program or add the program to the list of programs/apps that can be uninstalled.

**Describe alternatives you've considered**

**Additional context**
I have a Lenovo E595 with a 3500U APU Ryzen mobile processor and 8GB of DDR4 2400Mhz RAM and Win 10 64-bit Pro.

**Comment by JamesCJ60** [comment]
If you wish to uninstall it you can do so by deleting the extracted folder.

there are many reason to why you are having this issue. For example:
- OEM software not agreeing with AATU
- VRM thermal throttling 
- CPU thermal throttling 
- Needing auto reapply checked in the settings many
- etc
