### ISSUE TITLE
Current bios and/or applied APU settings

### ISSUE THREAD

**Issue by AndreoBotelho** [JamesCJ60/AMD-APU-Tuning-Utility#23]
Thanks for the great work, it is helping a lot.
What I'm missing from throttestop is a default/current values to save and reapply if need, it would be good to know if the settings are still applied or the driver/bios/EC had reseted it.

It is just a Tab or a side collum with the current APU power/clock configuration.

**Comment by JamesCJ60** [comment]
What you are asking is somewhat possible, as shown by AATU Extreme. The cavitate is that reading these sensors will cause anti-cheat software to flag AATU, as winring0 is required to read the APUs sensors. 

I am looking into alternatives, but there is nothing I can do as of now that can avoid this issue.
