### ISSUE TITLE
iGPU Overclocking not works on R5 5600H

### ISSUE THREAD

**Issue by flben233** [JamesCJ60/AMD-APU-Tuning-Utility#25]
**Describe the bug**
The iGPU overclock not work on 5600H.I changed the clock and apply,it told me successful,but gpu-z showed me it wasn't changed.You can see the screenshot.

**Expected behavior**
iGPU Overclocking works.

**Screenshots**
[Screenshot](https://s1.328888.xyz/2022/04/15/iD9Ye.png)

**Desktop (please complete the following information):**
OS: Windows 10 Home
Version: 21H2
Processor: AMD Ryzen 5 5600H with Radeon Graphics

**Comment by JamesCJ60** [comment]
As shown in the actual menu, iGPU control only works on Zen2 APUs aka the whole 4000 series and select 5000 series (5300U, 5500U, and 5700U). It does not work on Zen3 APUs.
