### ISSUE TITLE
Unable to extract zip file

### ISSUE THREAD

**Issue by chr1s2k** [JamesCJ60/AMD-APU-Tuning-Utility#27]
I am unable to extract the zip file.  I have tried on multiple computers.  Please see the attached screenshot
<img width="443" alt="AMDAPUTool" src="https://user-images.githubusercontent.com/23061884/165724364-5f9cd350-4887-4428-af5f-9fdeb1749b0c.PNG">
.

**Comment by JamesCJ60** [comment]
I believe this was an issue with the 7zip options I was using with gat build. This should now be fixed on newer builds.
