### ISSUE TITLE
Have future plan to support ryzen pro line?

### ISSUE THREAD

**Issue by Alexkim4** [JamesCJ60/AMD-APU-Tuning-Utility#28]
Hello
I'm laptop user which using ryzen pro line
It is sad that the ryzen pro line is not supported. Do you have any plans to support it in the future?
Thank You.

**Comment by JamesCJ60** [comment]
The Pro line up is supported, there’s zero difference between the Pro and non-Pro at a silicon level, only a few alterations at firmware level to enable extra security features.
