### ISSUE TITLE
Doesn't Auto Start on Windows Boot

### ISSUE THREAD

**Issue by DeSentinel** [JamesCJ60/AMD-APU-Tuning-Utility#36]
Thiked option to start when Windows boot. Nothing happend. Even created task schedule, nothing happend, moved shortcut to startup.. nothing happend. 

Im on Windows 10 21H2.
Latest AATU.
Also tried older version. Still nothing.

Lenovo Thinkpad A285, Ryzen 5 2500U

**Expected behavior**
Starts when Windows boots up.

**Comment by abdullah-alnami** [comment]
I have the same issue.

**Comment by Xarej** [comment]
Same here.
