### ISSUE TITLE
There is no actual source code of whole application

### ISSUE THREAD

**Issue by tribals** [JamesCJ60/AMD-APU-Tuning-Utility#37]
**Describe the bug**
Please stop releasing source code of this repository at "Releases" page: there is rarely *any* source of actual application. Where it is, btw?

**Comment by tribals** [comment]
I did. But where is the branch for actual code from which a current release of app was built? Not V2 or V3 but the code which will be run on my machine? I wat to review it before running it. None.

**Comment by nlutterman** [comment]
@tribals I don't know if you've noticed the README header, but you'd be likely running the application found here: https://github.com/JamesCJ60/Universal-x86-Tuning-Utility

The source is in the master branch there.
