### ISSUE TITLE
Unhandled exception - newtonsoft.json version

### ISSUE THREAD

**Issue by uros139** [JamesCJ60/AMD-APU-Tuning-Utility#4]
![Untitled](https://user-images.githubusercontent.com/76960898/131248649-2906f8ca-3c83-4bff-a288-9c053b66e025.jpg)
When i click continue, app shows in taskbar, but when i click on it, it won`t open.
I used earlier versions, and had no such a issue, last couple of version have it. I downloaded earlier version, and it works normal.

**Comment by JamesCJ60** [comment]
Delete the AATU folder and extract it again as ur missing files due to it not being extracted correctly from the zip file.
