### ISSUE TITLE
[Feature Request]: Add option to disable BD PROCHOT signal entirely similiar to Throttlestop

### ISSUE THREAD

**Issue by NaiveInvestigator** [JamesCJ60/AMD-APU-Tuning-Utility#44]
**Is your feature request related to a problem? Please describe.**
I have received my laptop (Lenovo Legion 5 15ARH05H with Ryzen 7 4800H ) after a repair but the laptop randomly starts thermal throttling even tho the temps are low. And I also haven't OC'd my CPU 

**Describe the solution you'd like**
Disabling the  BDPROCHOT signal would fix my issue entirely.

**Describe alternatives you've considered**
I have tried to limit power limits, undervolt, disable Turbo Boost, update BIOS and increasing the skin temperature but sadly it hasn't fixed it.

**Additional context**
![thermal throttling](https://user-images.githubusercontent.com/72654596/188255539-a86fde85-4c41-4128-9924-cfeab71361ab.png)

**Comment by JamesCJ60** [comment]
Hi, your issue is that external components are throttling resulting in the APU having to throttle to keep them cool. It’s likely the VRMs are throttling something that cannot be fixed in software.

**Comment by NaiveInvestigator** [comment]
I believe the sensors are malfunctioning, cause it is cool to the touch. Could we have this option as like an experimental or hidden feature? I see no reason not. Or could you point me to some resources where i can apply this to my own laptop? I know the risks involved ofc.

**Comment by JamesCJ60** [comment]
There is no way in software to work around it, an external component that is not being cooled properly is throttling causing the APU to throttle.

Only way to fix it is to find the power delivery component that is throttling and find away to cool it probably. Your best bet is to send the laptop back for them to fix it.

**Comment by NaiveInvestigator** [comment]
Aww that sucks, hopefully it gets fixed after I send them back then ig. Thanks for the help!
