### ISSUE TITLE
The gpu frequency is reset after restarting the laptop. 

### ISSUE THREAD

**Issue by Andrey22250** [JamesCJ60/AMD-APU-Tuning-Utility#48]
The gpu frequency is reset after restarting the laptop. Applying overclocking when turned on does not help.

**To Reproduce**
1. Go to 'Clock control'
2. Click on 'igpu clock' and on
3. Go to 'Settings'
4. Go to 'Clock control'
5. Igpu clock don't on
6. See error

**Expected behavior**
When re-entering the menu, the gpu frequency should not be turned off by itself. When restarting the laptop, gpu overclocking should be applied automatically

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win 10 21H2]
 - APU [Ryzen 5 6600H]
 - Version [e.g. beta 7]

**Additional context**

**Comment by JamesCJ60** [comment]
As of the latest releases you can now apply clock control menu settings on startup.
