### ISSUE TITLE
Gui not showing up after ticking  "start minimized" option in setting

### ISSUE THREAD

**Issue by Babbosh** [JamesCJ60/AMD-APU-Tuning-Utility#56]
**Describe the bug**
I ticked the start minimized box in settings and the gui doesn't show up anymore no matter what I do. Cannot find the icon in bar as well.

**To Reproduce**

**Expected behavior**

**Screenshots**

Laptop
 - OS: windows 10
 - APU Ryzen 7 4700u

**Additional context**

**Comment by JamesCJ60** [comment]
Should be fixed as of the latest release.
