### ISSUE TITLE
Software not working with Amd ryzen 7 5800h

### ISSUE THREAD

**Issue by Medohh2120** [JamesCJ60/AMD-APU-Tuning-Utility#65]
**Describe the bug**
AMD tuning utility Undervolting not working with Ryzen 5800h (Not first case).

**To Reproduce**
1. Go to 'AMD Tuning utility '
2. Click on 'CPU Overclocking'
3. Scroll down to 'Curve optimizer All Core'
4. Try to change value of voltage to negative or positive
5. Check apply curve optimizer curve
6. Hit apply.
7. Voltage won't change in HWINFO or change at all whatsoever (CPU is irresponsive)
**Expected behavior**
The CPU voltage should change but this specific CPU won't respond despite other ones like Ryzen 4600h responding easily and Ryzen 5800h being supported on Ryzen tuning utility description.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10 pro]
 - APU [Ryzen 7 5800h]
 - Version [Latest and also tried old versions and still didn't work]

**Additional context**
this is not the first case as other people in Youtube comment section had same issue with same chipset.
https://www.youtube.com/watch?v=QKOCFqNpyOU&ab_channel=potato

**Comment by JamesCJ60** [comment]
Hi, only Ryzen 9 mobile APUs can undervolt after the 4000 series using Curve Optimiser.
