### ISSUE TITLE
AATU 2.0.5.2 stable creates windows errors, force closes apps and even freezes computer

### ISSUE THREAD

**Issue by n0aaz** [JamesCJ60/AMD-APU-Tuning-Utility#7]
Since i've upgraded from 2.0.5.2 beta to the stable release, i've encountered 3 crashes in 24h that also appear as ryzenadj errors on the windows event manager: 
![image](https://user-images.githubusercontent.com/7826562/147497672-36c8bbc3-00cd-4870-b0bb-259ddd38e64c.png)

I'm only using adaptive eco on my computer that is an ASUS UM425IA (4700U , 16Gb ram) 

One of the 3 times, the computer completely froze except for the mouse that was moving at about 2-3fps and the trackpad wasn't responding, only the usb mouse. 
![image](https://user-images.githubusercontent.com/7826562/147497783-e563ba99-94c5-40a2-b86c-3e8a3185fb51.png)

Somehow windows also automatically force closes firefox when it doesn't freeze.

Came back to 2.0.5.2 beta and the issues haven't happened again.

**Comment by aisivan36** [comment]
Me to I am having error log  like this
![image](https://user-images.githubusercontent.com/23189900/147551690-ef1d213e-010c-4380-bcee-fb4a4acc58ab.png)

**Comment by n0aaz** [comment]
> Me to I am having error log like this ![image](https://user-images.githubusercontent.com/23189900/147551690-ef1d213e-010c-4380-bcee-fb4a4acc58ab.png)

What laptop and what CPU do you have?

**Comment by aisivan36** [comment]
> > Me to I am having error log like this 
> 
> What laptop and what CPU do you have?

HP Omen 15 Ryzen 4800H

**Comment by JamesCJ60** [comment]
The issues shown here are to do with RyzenADJ itself, not AATU. I have passed this on to the RyzenADJ devs to fix in a future release. Thanks for reporting them though.
